insert into planet (ID, Name) values ('A', 'Earth');
insert into planet (ID, Name) values ('B', 'Moon');
insert into planet (ID, Name) values ('C', 'Jupiter');
insert into planet (ID, Name) values ('D', 'Venus');
insert into planet (ID, Name) values ('E', 'Mars');
insert into planet (ID, Name) values ('F', 'Saturn');
insert into planet (ID, Name) values ('G', 'Uranus');
insert into planet (ID, Name) values ('H', 'Pluto');
insert into planet (ID, Name) values ('I', 'Neptune');
insert into planet (ID, Name) values ('J', 'Mercury');
insert into planet (ID, Name) values ('K', 'Alpha Centauri');
insert into planet (ID, Name) values ('L', 'Luhman 16');
insert into planet (ID, Name) values ('M', 'Epsilon Eridani');
insert into planet (ID, Name) values ('N', 'Groombridge 34');
insert into planet (ID, Name) values ('O', 'Epsilon Indi');
insert into planet (ID, Name) values ('P', 'Tau Ceti');
insert into planet (ID, Name) values ('Q', 'Kapteyn''s star');
insert into planet (ID, Name) values ('R', 'Gliese 687');
insert into planet (ID, Name) values ('S', 'Gliese 674');
insert into planet (ID, Name) values ('T', 'Gliese 876#');
insert into planet (ID, Name) values ('U', 'Gliese 832');
insert into planet (ID, Name) values ('V', 'Fomalhaut');
insert into planet (ID, Name) values ('W', 'Virginis');
insert into planet (ID, Name) values ('X', 'HD 102365');
insert into planet (ID, Name) values ('Y', 'Gliese 176');
insert into planet (ID, Name) values ('Z', 'Gliese 436');
insert into planet (ID, Name) values ('A''', 'Pollux');
insert into planet (ID, Name) values ('B''', 'Gliese 86');
insert into planet (ID, Name) values ('C''', 'HIP 57050');
insert into planet (ID, Name) values ('D''', 'Piscium');
insert into planet (ID, Name) values ('E''', 'GJ 1214');
insert into planet (ID, Name) values ('F''', 'Upsilon Andromedae');
insert into planet (ID, Name) values ('G''', 'Gamma Cephei');
insert into planet (ID, Name) values ('H''', 'HD 176051');
insert into planet (ID, Name) values ('I''', 'Gliese 317');
insert into planet (ID, Name) values ('J''', 'HD 38858');
insert into planet (ID, Name) values ('K''', 'Ursae Majoris');

insert into route (OriginID, DestinationID, Distance) values ('A', 'B', 0.44);
insert into route (OriginID, DestinationID, Distance) values ('A', 'C', 1.89);
insert into route (OriginID, DestinationID, Distance) values ('A', 'D', 0.1);
insert into route (OriginID, DestinationID, Distance) values ('B', 'H', 2.44);
insert into route (OriginID, DestinationID, Distance) values ('B', 'E', 3.45);
insert into route (OriginID, DestinationID, Distance) values ('C', 'F', 0.49);
insert into route (OriginID, DestinationID, Distance) values ('D', 'L', 2.34);
insert into route (OriginID, DestinationID, Distance) values ('D', 'M', 2.61);
insert into route (OriginID, DestinationID, Distance) values ('H', 'G', 3.71);
insert into route (OriginID, DestinationID, Distance) values ('E', 'I', 8.09);
insert into route (OriginID, DestinationID, Distance) values ('F', 'J', 5.46);
insert into route (OriginID, DestinationID, Distance) values ('F', 'K', 3.67);
insert into route (OriginID, DestinationID, Distance) values ('G', 'Z', 5.25);
insert into route (OriginID, DestinationID, Distance) values ('I', 'Z', 13.97);
insert into route (OriginID, DestinationID, Distance) values ('I', 'J', 14.78);
insert into route (OriginID, DestinationID, Distance) values ('L', 'T', 15.23);
insert into route (OriginID, DestinationID, Distance) values ('T', 'N', 10.43);
insert into route (OriginID, DestinationID, Distance) values ('T', 'S', 14.22);
insert into route (OriginID, DestinationID, Distance) values ('S', 'O', 6.02);
insert into route (OriginID, DestinationID, Distance) values ('O', 'U', 5.26);
insert into route (OriginID, DestinationID, Distance) values ('J', 'R', 12.34);
insert into route (OriginID, DestinationID, Distance) values ('R', 'P', 10.1);
insert into route (OriginID, DestinationID, Distance) values ('R', 'L''', 9.95);
insert into route (OriginID, DestinationID, Distance) values ('Z', 'Y', 18.91);
insert into route (OriginID, DestinationID, Distance) values ('Y', 'Q', 22.04);
insert into route (OriginID, DestinationID, Distance) values ('Q', 'X', 10.51);
insert into route (OriginID, DestinationID, Distance) values ('L''', 'X', 23.61);
insert into route (OriginID, DestinationID, Distance) values ('X', 'K''', 19.94);
insert into route (OriginID, DestinationID, Distance) values ('P', 'U', 9.31);
insert into route (OriginID, DestinationID, Distance) values ('U', 'K''', 21.23);
insert into route (OriginID, DestinationID, Distance) values ('U', 'J''', 25.96);
insert into route (OriginID, DestinationID, Distance) values ('J''', 'V', 3.16);
insert into route (OriginID, DestinationID, Distance) values ('K''', 'V', 20.42);
insert into route (OriginID, DestinationID, Distance) values ('J''', 'I''', 17.1);
insert into route (OriginID, DestinationID, Distance) values ('Y', 'A''', 19.52);
insert into route (OriginID, DestinationID, Distance) values ('A''', 'B''', 31.56);
insert into route (OriginID, DestinationID, Distance) values ('B''', 'C''', 23.13);
insert into route (OriginID, DestinationID, Distance) values ('K''', 'W', 28.89);
insert into route (OriginID, DestinationID, Distance) values ('W', 'C''', 10.64);
insert into route (OriginID, DestinationID, Distance) values ('W', 'E''', 36.19);
insert into route (OriginID, DestinationID, Distance) values ('C''', 'D''', 36.48);
insert into route (OriginID, DestinationID, Distance) values ('E''', 'E''', 41.26);
insert into route (OriginID, DestinationID, Distance) values ('E''', 'F''', 42.07);
insert into route (OriginID, DestinationID, Distance) values ('F''', 'G''', 17.63);
insert into route (OriginID, DestinationID, Distance) values ('G''', 'H''', 40.48);
